---
# NOTE(zstyblik):
# * mod files should have 2 dig prefix
# * mod confs go elsewhere(?) and don't have 2 dig prefix
- name: Check mod configuration against spec file
  ansible.builtin.validate_argument_spec:
    argument_spec: |
      {{
        (
          lookup(
            'ansible.builtin.file',
            'specs/apache_conf_argument_specs.yml'
          ) | from_yaml
        )['argument_specs']['apache_conf_item']['options']
      }}
    provided_arguments: "{{ _apache_mod_item }}"

- name: Create config file for Apache module.
  ansible.builtin.copy:
    content: "{{ _apache_mod_item.conf_content }}"
    dest: "{{ apache_httpd_mod_conf_deploy_dir }}/{{ _apache_mod_item.name }}.conf"
    owner: root
    group: root
    mode: '0644'
  when:
    - _apache_mod_item.state | default('present') == 'present'
    - _apache_mod_item.conf_content is defined
  notify: restart apache
  become: true

- name: Disable and delete Apache module conf file.
  ansible.builtin.file:
    path: "{{ apache_httpd_mod_conf_deploy_dir }}/{{ _apache_mod_item.name }}.conf"
    state: absent
  when: |
    _apache_mod_item.state | default('present') != 'present'
    or _apache_mod_item.conf_content is not defined
  notify: restart apache
  become: true

- name: Enable Apache module.
  ansible.builtin.copy:
    content: "{{ _apache_mod_item.mod_content }}"
    dest: "{{ apache_httpd_mod_deploy_dir }}/99-{{ _apache_mod_item.name }}.conf"
    owner: root
    group: root
    mode: '0644'
  when:
    - _apache_mod_item.state | default('present') == 'present'
    - _apache_mod_item.mod_content is defined
  notify: restart apache
  become: true

- name: Disable and delete Apache module file.
  ansible.builtin.file:
    path: "{{ apache_httpd_mod_deploy_dir }}/99-{{ _apache_mod_item.name }}.conf"
    state: absent
  when:
    - _apache_mod_item.state | default('present') != 'present'
  notify: restart apache
  become: true
