---
name: CI for ansible-role-apache

on: [push]  # yamllint disable-line rule:truthy

defaults:
  run:
    working-directory: 'zstyblik.apache'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4
        with:
          path: 'zstyblik.apache'
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-ci.txt
      - name: Run yamllint
        run: |
          ./ci/run-yamllint.sh
      - name: Run ansible-lint
        run: |
          ./ci/run-ansible-lint.sh
      - name: Reorder Python imports
        run: |
          ./ci/run-reorder-python-imports.sh
      - name: Lint with flake8
        run: |
          ./ci/run-flake8.sh
      - name: Lint with black
        run: |
          ./ci/run-black.sh check || ( ./ci/run-black.sh diff; exit 1 )
      - name: Test with pytest
        run: |
          ./ci/run-pytest.sh
